---
  controller: 
    metrics: 
      enabled: true
      serviceMonitor: 
        selector: true
  server: 
    service: 
      type: "ClusterIP"
  repoServer: 
    metrics: 
      enabled: true
      serviceMonitor: 
        selector: true
  dex: 
    enabled: true
  redis: 
    enabled: true