---
  controller: 
    metrics: 
      enabled: true
      serviceMonitor: 
        selector: true
  server: 
    service: 
      type: "LoadBalancer"
    ingress:
      annotations: {
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
      }
  repoServer: 
    metrics: 
      enabled: true
      serviceMonitor: 
        selector: true
  dex: 
    enabled: true
  redis: 
    enabled: true