---
  controller: 
    metrics: 
      enabled: true
      serviceMonitor: 
        selector: true
  server: 
    service: 
      type: "LoadBalancer"
    ingress:
      annotations: {
        kubernetes.io/ingress.class: "nginx",
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true",
        nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      }
  repoServer: 
    metrics: 
      enabled: true
      serviceMonitor: 
        selector: true
  dex: 
    enabled: true
  redis: 
    enabled: true